"""Tool synthesis — the meta-tools that let Daedalus extend itself.

These are presented to the model alongside ordinary tools. `create_tool` is the
mechanism by which the agent grows: it writes a tool, we test it in the sandbox,
and on success we persist + register it so it is callable immediately afterward.
"""

from __future__ import annotations

import json
import keyword
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .config import GENERATED_DIR, MANIFEST_PATH
from .sandbox import run_self_test
from .toolbox import Toolbox

_FILE_HEADER = '''\
"""Auto-generated by Daedalus on {ts}.

Forged to satisfy the task:
  {task}
"""

SCHEMA = {schema}


{code}
'''


@dataclass
class SynthesisResult:
    message: str            # text fed back to the model
    created_tool: str | None = None


@dataclass
class Synthesizer:
    toolbox: Toolbox
    task: str = ""
    events: list[str] = field(default_factory=list)

    META_TOOLS = [
        {
            "name": "create_tool",
            "description": (
                "Forge a NEW reusable tool and add it to your permanent toolbox. Use this "
                "whenever a task needs a capability you do not already have (math, parsing, "
                "transforms, web access, etc.). The tool is tested in a sandbox before it is "
                "accepted; if the test fails you get the error and may call create_tool again "
                "to fix it. Prefer small, single-purpose, well-named tools you can reuse later."
            ),
            "input_schema": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "snake_case tool name (a valid Python identifier).",
                    },
                    "description": {
                        "type": "string",
                        "description": "One-sentence description of what the tool does.",
                    },
                    "input_schema": {
                        "type": "object",
                        "description": "JSON Schema (object) describing the tool's parameters.",
                    },
                    "python_code": {
                        "type": "string",
                        "description": (
                            "Python source that defines `def run(**kwargs)` returning a string. "
                            "May include helper functions and stdlib imports. No top-level side effects."
                        ),
                    },
                    "test_code": {
                        "type": "string",
                        "description": (
                            "A self-test that calls run(...) with sample args and uses `assert` to "
                            "verify the result. It runs right after your code; reference `run` directly."
                        ),
                    },
                },
                "required": ["name", "description", "input_schema", "python_code", "test_code"],
            },
        },
        {
            "name": "list_tools",
            "description": "List every tool currently available (primitive and forged), with descriptions.",
            "input_schema": {"type": "object", "properties": {}, "required": []},
        },
    ]

    # -- dispatch ----------------------------------------------------------
    def is_meta(self, name: str) -> bool:
        return name in {t["name"] for t in self.META_TOOLS}

    def handle(self, name: str, payload: dict) -> SynthesisResult:
        if name == "create_tool":
            return self._create_tool(payload)
        if name == "list_tools":
            return SynthesisResult(self._list_tools())
        return SynthesisResult(f"ERROR: unknown meta-tool {name!r}")

    # -- implementations ---------------------------------------------------
    def _list_tools(self) -> str:
        lines = []
        for spec in self.toolbox.specs():
            lines.append(f"- {spec['name']}: {spec['description']}")
        return "Available tools:\n" + "\n".join(lines)

    def _create_tool(self, payload: dict) -> SynthesisResult:
        name = payload.get("name", "")
        if not name.isidentifier() or keyword.iskeyword(name):
            return SynthesisResult(f"ERROR: {name!r} is not a valid Python identifier.")
        if self.toolbox.has(name):
            return SynthesisResult(
                f"ERROR: a tool named {name!r} already exists — reuse it instead of recreating it."
            )

        code = payload["python_code"]
        if "def run(" not in code:
            return SynthesisResult("ERROR: python_code must define `def run(**kwargs)`.")

        # 1. Sandbox the candidate before trusting it.
        result = run_self_test(code, payload["test_code"])
        if not result.ok:
            return SynthesisResult(
                f"Tool {name!r} FAILED its self-test and was NOT saved.\n"
                f"--- test output ---\n{result.output}\n"
                f"Fix the code or test and call create_tool again."
            )

        # 2. Persist it.
        schema = {
            "name": name,
            "description": payload["description"],
            "input_schema": payload["input_schema"],
        }
        ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
        file_text = _FILE_HEADER.format(
            ts=ts,
            task=self.task or "(ad-hoc)",
            schema=json.dumps(schema, indent=4),
            code=code.strip(),
        )
        path = GENERATED_DIR / f"{name}.py"
        path.write_text(file_text, encoding="utf-8")

        # 3. Register live so it's usable on the next turn.
        self.toolbox.register_from_file(path)
        self._record_manifest(name, schema["description"], ts)
        self.events.append(name)

        return SynthesisResult(
            f"Tool {name!r} passed its self-test and is now in your permanent toolbox. "
            f"You can call it now.",
            created_tool=name,
        )

    def _record_manifest(self, name: str, description: str, ts: str) -> None:
        entries = []
        if MANIFEST_PATH.is_file():
            try:
                entries = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                entries = []
        entries.append(
            {"name": name, "description": description, "created_at": ts, "task": self.task}
        )
        MANIFEST_PATH.write_text(json.dumps(entries, indent=2), encoding="utf-8")
